swagger: '2.0'
info:
  title: API de Unidades de Saúde
  description: API para obter informações sobre unidades de saúde
  version: 1.0.0  
paths:
  /api/unidades_de_saude:
    get:
      summary: Lista de Unidades de Saúde
      description: Retorna uma lista de unidades de saúde baseado em filtros.
      parameters:
        - in: query
          name: abrangencia
          type: string
          description: Filtro por abrangência
        - in: query
          name: uf
          type: string
          description: Filtro por estado
        - in: query
          name: isFullTime
          type: string
          description: Filtro por período integral
      responses:
        '200':
          description: Sucesso
          schema:
            type: array
            items:
              type: object
              properties:
                id:
                  type: integer
                  description: ID da unidade de saúde
                nome:
                  type: string
                  description: Nome da unidade de saúde
                endereco:
                  type: string
                  description: Endereço da unidade de saúde
                abrangencia:
                  type: string
                  description: Abrangência da unidade de saúde
                bairro:
                  type: string
                  description: Bairro da unidade de saúde
                cidade:
                  type: string
                  description: Cidade da unidade de saúde
                uf:
                  type: string
                  description: Estado da unidade de saúde
        '404':
          description: Nenhuma unidade de saúde encontrada
  /api/unidades_de_saude/id/{id}:
    get:
      summary: Detalhes da Unidade de Saúde
      description: Retorna detalhes de uma unidade de saúde pelo seu ID.
      parameters:
        - in: path
          name: id
          type: integer
          required: true
          description: ID da unidade de saúde
      responses:
        '200':
          description: Sucesso
          schema:
            type: object
            properties:
              id:
                type: integer
                description: ID da unidade de saúde
              nome:
                type: string
                description: Nome da unidade de saúde
              endereco:
                type: string
                description: Endereço da unidade de saúde
              abrangencia:
                type: string
                description: Abrangência da unidade de saúde
              bairro:
                type: string
                description: Bairro da unidade de saúde
              cidade:
                type: string
                description: Cidade da unidade de saúde
              uf:
                type: string
                description: Estado da unidade de saúde
        '404':
          description: Unidade de saúde não encontrada
